# Generated by Django 3.0.2 on 2020-07-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('businessStatus', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=50)),
                ('googleMapsURL', models.CharField(max_length=200)),
                ('openingHours', models.CharField(blank=True, max_length=200)),
                ('priceLevel', models.IntegerField(blank=True)),
                ('rating', models.FloatField(blank=True)),
                ('ratingCount', models.IntegerField(blank=True)),
            ],
        ),
    ]
