# Generated by Django 3.0.2 on 2020-07-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_remove_input_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='input',
            name='startDate',
            field=models.DateField(),
        ),
    ]
