# Generated by Django 3.1 on 2020-08-30 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20200724_0129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.RemoveField(
            model_name='place',
            name='businessStatus',
        ),
        migrations.RemoveField(
            model_name='place',
            name='openingHours',
        ),
    ]
