# Generated by Django 3.1 on 2020-08-31 19:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20200830_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
