# Generated by Django 3.1 on 2020-08-31 19:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20200831_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('is_club', models.BooleanField()),
                ('googleMapsURL', models.CharField(blank=True, max_length=500)),
                ('priceLevel', models.IntegerField(blank=True)),
                ('rating', models.FloatField(blank=True)),
                ('ratingCount', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='priceLevel',
        ),
        migrations.RemoveField(
            model_name='place',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='ratingCount',
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='googleMapsURL',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
