# Generated by Django 3.1 on 2020-09-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20200831_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
