# Generated by Django 3.1 on 2020-09-01 23:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_onedayplan_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='user',
            new_name='belongs_to_user',
        ),
        migrations.AddField(
            model_name='onedayplan',
            name='arrangement',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onedayplan',
            name='sleeping_place',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
