# Generated by Django 3.1 on 2020-09-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20200901_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedayplan',
            name='theme',
            field=models.CharField(default='no theme', max_length=30),
        ),
    ]
